## ui.R script ##
source("global.R")

header <- shinydashboard::dashboardHeader(title = "SiReX")

sidebar <- shinydashboard::dashboardSidebar(
	shinydashboard::sidebarMenu(
		shinydashboard::menuItem("Introduction", tabName = "introductionTab", icon = shiny::icon("info")),
		shinydashboard::menuItem("Data", tabName = "dataTab", icon = shiny::icon("database")),
		shinydashboard::menuItem("View uploaded data", tabName = "viewDataTab", icon = shiny::icon("search")),
		shinydashboard::menuItem("Summary statistics", tabName = "summaryStatisticsTab", icon = shiny::icon("list-ol")),
		shinydashboard::menuItem("Plots", tabName = "plotsTab", icon = shiny::icon("bar-chart")),
		shinydashboard::menuItem("Feedback and comments", href = "mailto:ag475@leicester.ac.uk?Subject=SiReX%20feedback%20and%20comments", icon = shiny::icon("commenting")),
		shinydashboard::menuItem("Issues and bug report", href = "https://github.com/ellessenne/sirex/issues/", icon = icon("exclamation-triangle ")),
		shinydashboard::menuItem("Source code", href = "https://github.com/ellessenne/sirex/", icon = shiny::icon("github"))
	)
)

body <- shinydashboard::dashboardBody(
	shiny::tags$head(
		shiny::tags$link(rel = "stylesheet", type = "text/css", href = "theme.css")
	),
	shinydashboard::tabItems(
		shinydashboard::tabItem(tabName = "introductionTab"),

		shinydashboard::tabItem(tabName = "dataTab",
														shinydashboard::box(width = 12,
																								solidHeader = TRUE,
																								shiny::p("Use the form below to upload your dataset."),
																								shiny::p("The file can be a comma-separated (.csv) file, a Stata version 8-14 file (.dta), an SPSS file (.sav), a SAS file (.sas7bdat), or an R serialised file (.rds). You can either upload a file stored on your computer or provide a link to an online file (e.g. on GitHub). Files ending in .gz, .bz2, .xz, or .zip will be automatically uncompressed. Files starting with http://, https://, ftp://, or ftps:// will be automatically downloaded. Remote gz files can also be automatically downloaded and decompressed."),
																								shiny::p("The dataset must be in tidy format, with variables in columns and observations in rows. See", shiny::a(href = "https://www.jstatsoft.org/article/view/v059i10", "here"), "for more details on tidy data. The app can handle a single estimand at once, and the uploaded dataset must include the following variables:"),
																								shiny::tags$ul(
																									shiny::tags$li("A variable representing an estimated coefficient or value from the simulation study;"),
																									shiny::tags$li("A variable representing the standard error of the estimated coefficient;"),
																									shiny::tags$li("A variable representing the true value of a given parameter.")),
																								shiny::p("Additionally, a dataset could contain the following variables:"),
																								shiny::tags$ul(
																									shiny::tags$li("A variable representing methods compared with the simulation study;"),
																									shiny::tags$li("A list of variables representing", shiny::em("by"), "factors that identify the various data-generating mechanisms, such as sample size, true distribution, etc.")),
																								shiny::p("It will be possible to define each variable after uploading a data set to SiReX.")),
														shinydashboard::box(width = 12,
																								solidHeader = TRUE,
																								shiny::p("Select method for uploading data:"),
																								shiny::radioButtons(inputId = "typeDataUpload",
																																		label = NULL,
																																		choices = c("Upload file" = "uploadData", "Link file" = "linkData", "Paste file" = "pasteData"),
																																		selected = "uploadData",
																																		inline = TRUE),
																								shiny::uiOutput(outputId = "loadData")),
														# using shiny::fluidRow fixes overflowing of following1 shinydashboard::box() elements
														shinydashboard::box(width = 4,
																								solidHeader = TRUE,
																								shiny::h1("Define variables:"),
																								shiny::selectInput(inputId = "defineEstvarname",
																																	 label = "Point estimates:",
																																	 choices = ""),
																								shiny::selectInput(inputId = "defineSe",
																																	 label = "Standard errors:",
																																	 choices = ""),
																								shiny::numericInput(inputId = "defineTrue",
																																		label = "True value:",
																																		value = 0)),
														shinydashboard::box(width = 4,
																								solidHeader = TRUE,
																								shiny::h1("Define methods:"),
																								shiny::selectInput(inputId = "defineMethod",
																																	 label = "Method variable:",
																																	 choices = ""),
																								shiny::selectInput(inputId = "defineRefMethod",
																																	 label = "Reference method:",
																																	 choices = "")),
														shinydashboard::box(width = 4,
																								solidHeader = TRUE,
																								shiny::h1("Define by factors:"),
																								shiny::selectInput(inputId = "defineBy",
																																	 label = "By factors:",
																																	 choices = "",
																																	 multiple = TRUE))
		),
		shinydashboard::tabItem(tabName = "viewDataTab",
														shinydashboard::box(width = 12,
																								solidHeader = TRUE,
																								shiny::dataTableOutput(outputId = "uploadedDataTable"))),
		shinydashboard::tabItem(tabName = "summaryStatisticsTab",
														shinydashboard::tabBox(
															width = 12,
															shiny::tabPanel("View summary statistics",
																							shiny::dataTableOutput(outputId = "summaryStatisticsDataTable")),
															shiny::tabPanel("Export table",
																							shiny::sliderInput(inputId = "summaryStatisticsLaTeXDigits",
																																 label = "Number of significant digits:",
																																 min = 0,
																																 max = 10,
																																 value = 4,
																																 step = 1,
																																 round = TRUE),
																							shiny::textInput(inputId = "summaryStatisticsLaTeXCaption",
																															 label = "Table caption:"),
																							shiny::verbatimTextOutput(outputId = "summaryStatisticsLaTeX")),
															shiny::tabPanel("Export data",
																							shiny::radioButtons(inputId = "exportSummaryStatisticsType",
																																	label = "Format of the file to export:",
																																	choices = c("Comma-separated" = "csv", "Tab-separated" = "tsv", "R" = "r", "Stata" = "stata", "SPSS" = "spss", "SAS" = "sas"),
																																	selected = "csv",
																																	inline = TRUE),
																							shiny::textInput(inputId = "exportSummaryStatisticsName",
																															 label = "Name the file to export:",
																															 value = "summary_statistics"),
																							shiny::downloadButton(outputId = "exportSummaryStatisticsButton",
																																		label = "Export",
																																		icon = shiny::icon("download"))))),
		shinydashboard::tabItem(tabName = "plotsTab",
														shinydashboard::box(
															width = 2,
															solidHeader = TRUE,
															shiny::p("Define facets:"),
															shiny::selectInput(inputId = "plotFacetX",
																								 label = "Select X-axis faceting variable:",
																								 choices = "",
																								 multiple = TRUE),
															shiny::selectInput(inputId = "plotFacetY",
																								 label = "Select Y-axis faceting variable:",
																								 choices = "",
																								 multiple = TRUE),
															shiny::p("Customise plot:"),
															shiny::textInput(inputId = "customXlab", label = "X-axis label:"),
															shiny::textInput(inputId = "customYlab", label = "Y-axis label:"),
															shiny::numericInput("plotWidth", "Plot width:", value = 6, min = 1, max = 50),
															shiny::numericInput("plotHeight", "Plot height:", value = 6, min = 1, max = 50),
															shiny::numericInput("plotResolution", "Plot resolution (in DPI):", value = 150, min = 72, max = 320),
															shiny::radioButtons("plotFormat", label = "Format", choices = c("png", "pdf"), selected = "png")),
														shinydashboard::tabBox(
															width = 10,
															shiny::tabPanel("Plot estimates",
																							shiny::radioButtons(inputId = "selectPlotEstimates",
																																	label = "Select plot type:",
																																	choices = c("Point estimates vs SEs" = "b_vs_se"),
																																	inline = TRUE),
																							shiny::plotOutput(outputId = "outPlotEstimates", width = "100%"),
																							shiny::verbatimTextOutput(outputId = "outPlotEstimatesCode")),
															shiny::tabPanel("Plot summary statistics",
																							div(style = "display: inline-block; vertical-align:top; margin: 0 auto;",
																									shiny::selectInput(inputId = "selectPlotSummaryStat",
																																		 label = "Select summary statistic:",
																																		 choices = c("Non-missing point estimates" = "bsims",
																																		 						"Non-missing standard errors" = "sesims",
																																		 						"Bias in point estimate" = "bias",
																																		 						"Empirical standard error" = "esd",
																																		 						"Mean squared error" = "mse",
																																		 						"% gain in precision relative to reference method" = "relprec",
																																		 						"Model-based standard error" = "modelse",
																																		 						"Relative % error in standard error" = "relerror",
																																		 						"Coverage of nominal 95% confidence interval" = "cover",
																																		 						"Power of 5% level test" = "power"))),
																							div(style = "display: inline-block; vertical-align:top; margin: 0 auto;",
																									shiny::selectInput(inputId = "selectPlotSummary",
																																		 label = "Select plot type:",
																																		 choices = c("Barplot" = "barplot",
																																		 						"Lollyplot" = "lollyplot"))),
																							shiny::plotOutput(outputId = "outPlotSummary", width = "100%"),
																							shiny::verbatimTextOutput(outputId = "outPlotSummaryCode"))
														)
		)
	)
)

shinydashboard::dashboardPage(header, sidebar, body)
